package model;

import javax.swing.AbstractListModel;
import twitter4j.Trend;
import twitter4j.Trends;

/**
 * This class stores all of the trends gathered from the controller. The
 * class extends the AbstractListModel class so that we may display the
 * information on a JList in the GUI.
 *
 * @version 2.0
 * @author Danny Selgo
 */
public class TrendModel extends AbstractListModel{
	
	private Trend[] trends;
	
	/**
	 * Constructor for the TrendModel.  Stores the list of trends generated by the controller.
	 * 
	 * @param trends the trends generated by the controller.
	 */
	public TrendModel(Trends trends)	{
		this.trends = trends.getTrends();
	}
	
	/**
	 * Returns the number of trends stored in the TrendModel.
	 * 
	 * @return returns the number of trends stored in the TrendModel.
	 */
	public int getSize() {
		return trends.length;
	}
	
	/**
	 * Returns the trend at the given index.
	 * 
	 * @param index the index of the trend desired.
	 * @return the trend at the given index.
	 */
	public String getElementAt(int index) {
		return trends[index].getName();
	}
}
