package model;

import javax.swing.AbstractListModel;
import twitter4j.ResponseList;
import twitter4j.User;

/**
 * This class stores all of the users that Twitter suggests to follow 
 * gathered from the controller. The class extends the AbstractListModel 
 * class so that we may display the information on a JList in the GUI.
 *
 * @version 2.0
 * @author Danny Selgo
 */
public class UserModel extends AbstractListModel {
	
	/** ResponseList of Users. */
	private ResponseList<User> users;
	
	public UserModel() {
		users = null;
	}
	
	/**
	 * Constructor for the UserModel.  Stores the list of users generated 
	 * by the controller.
	 * 
	 * @param users the ResponseList of users generated by the controller.
	 */
	public UserModel(final ResponseList<User> users) {
		this.users = users;
	}
	
	/**
	 * Returns the number of users stored in the UserModel.
	 * 
	 * @return returns the number of users stored in the UserModel.
	 */
	public int getSize() {
		return users.size();
	}
	
	/**
	 * Returns the screen name of the user at the given index.
	 * 
	 * @param index the index of the user desired.
	 * @return the screen name of the user at the given index.
	 */
	public String getElementAt(final int index) {
		return users.get(index).getScreenName();
	}
}
