/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.logging.Logger;
import javax.swing.*;
import controller.*;
import model.*;



/**
 *
 * @author Morgan
 */
public class Twitter4JGUI extends javax.swing.JFrame {

    /**
     * Creates new form Twitter4JGUI
     */
    public Twitter4JGUI() {
        engine = new TwitterEngine();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        switchAccountDialog = new javax.swing.JDialog();
        switchAccountPanel = new javax.swing.JPanel();
        switchAccountPromptLabel = new javax.swing.JLabel();
        consumerKeyLabel = new javax.swing.JLabel();
        consumerSecretLabel = new javax.swing.JLabel();
        accessTokenLabel = new javax.swing.JLabel();
        accessTokenSecretLabel = new javax.swing.JLabel();
        consumerKeyTextField = new javax.swing.JTextField();
        consumerSecretTextField = new javax.swing.JTextField();
        accessTokenTextField = new javax.swing.JTextField();
        accessTokenSecretTextField = new javax.swing.JTextField();
        switchAccountDialogButton = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        mainTabPane = new javax.swing.JTabbedPane();
        createTweetPanel = new javax.swing.JPanel();
        enterTweetLabel = new javax.swing.JLabel();
        tweetTextArea = new javax.swing.JScrollPane();
        enterTweetTextArea = new javax.swing.JTextArea();
        updateButton = new javax.swing.JButton();
        searchTopicsPanel = new javax.swing.JPanel();
        searchTopicLabel = new javax.swing.JLabel();
        searchTopicTextField = new javax.swing.JTextField();
        searchTopicsButton = new javax.swing.JButton();
        searchPeoplePanel = new javax.swing.JPanel();
        searchPeopleLabel = new javax.swing.JLabel();
        searchPeopleTextField = new javax.swing.JTextField();
        searchPeopleButton = new javax.swing.JButton();
        profilePanel = new javax.swing.JPanel();
        profileLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        followingLabel = new javax.swing.JLabel();
        followersLabel = new javax.swing.JLabel();
        nameLabelContent = new javax.swing.JLabel();
        displayNameLabelContent = new javax.swing.JLabel();
        followingLabelContent = new javax.swing.JLabel();
        followersLabelContent = new javax.swing.JLabel();
        tweetLabel = new javax.swing.JLabel();
        tweetContentLabel = new javax.swing.JLabel();
        timelineButton = new javax.swing.JButton();
        twitterPic = new javax.swing.JLabel();
        switchAccountButton = new javax.swing.JButton();
        tweetTableScrollPane = new javax.swing.JScrollPane();
        tweetTable = new JTable(engine.getTable());
        displayTweetText = new javax.swing.JTextArea();
        followButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        retweetButton = new javax.swing.JButton();
        trendsFollowersPanel = new javax.swing.JPanel();
        trendLabel = new javax.swing.JLabel();
        followerLabel = new javax.swing.JLabel();
        trendsListScrollPane = new javax.swing.JScrollPane();
        trendsList = new javax.swing.JList();
        followersListScrollPane = new javax.swing.JScrollPane();
        followersList = new javax.swing.JList();
        menubar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        refreshMenuItem = new javax.swing.JMenuItem();
        quitMenuItem = new javax.swing.JMenuItem();
        helpMenuBar = new javax.swing.JMenu();
        getHelpMenuItem = new javax.swing.JMenuItem();

        switchAccountDialog.setMinimumSize(new java.awt.Dimension(400, 275));
        switchAccountDialog.setResizable(false);

        switchAccountPromptLabel.setText("Please enter the following information to switch accounts:");

        consumerKeyLabel.setText("Consumer Key:");

        consumerSecretLabel.setText("Consumer Secret:");

        accessTokenLabel.setText("Access Token:");

        accessTokenSecretLabel.setText("Access Token Secret:");

        consumerKeyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consumerKeyTextFieldActionPerformed(evt);
            }
        });

        accessTokenTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accessTokenTextFieldActionPerformed(evt);
            }
        });

        switchAccountDialogButton.setText("OK");
        switchAccountDialogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchAccountDialogButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout switchAccountPanelLayout = new javax.swing.GroupLayout(switchAccountPanel);
        switchAccountPanel.setLayout(switchAccountPanelLayout);
        switchAccountPanelLayout.setHorizontalGroup(
            switchAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(switchAccountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(switchAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(switchAccountPanelLayout.createSequentialGroup()
                        .addComponent(switchAccountPromptLabel)
                        .addGap(0, 84, Short.MAX_VALUE))
                    .addGroup(switchAccountPanelLayout.createSequentialGroup()
                        .addGroup(switchAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accessTokenSecretLabel)
                            .addComponent(accessTokenLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(consumerSecretLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(consumerKeyLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(switchAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(consumerKeyTextField)
                            .addComponent(consumerSecretTextField)
                            .addComponent(accessTokenTextField)
                            .addComponent(accessTokenSecretTextField))))
                .addContainerGap())
            .addGroup(switchAccountPanelLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(switchAccountDialogButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        switchAccountPanelLayout.setVerticalGroup(
            switchAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(switchAccountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(switchAccountPromptLabel)
                .addGap(18, 18, 18)
                .addGroup(switchAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consumerKeyLabel)
                    .addComponent(consumerKeyTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(switchAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consumerSecretLabel)
                    .addComponent(consumerSecretTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(switchAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accessTokenLabel)
                    .addComponent(accessTokenTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(switchAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accessTokenSecretLabel)
                    .addComponent(accessTokenSecretTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(switchAccountDialogButton))
        );

        javax.swing.GroupLayout switchAccountDialogLayout = new javax.swing.GroupLayout(switchAccountDialog.getContentPane());
        switchAccountDialog.getContentPane().setLayout(switchAccountDialogLayout);
        switchAccountDialogLayout.setHorizontalGroup(
            switchAccountDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, switchAccountDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(switchAccountPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        switchAccountDialogLayout.setVerticalGroup(
            switchAccountDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, switchAccountDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(switchAccountPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Twitter Desktop Application");
        setBackground(javax.swing.UIManager.getDefaults().getColor("Menu.selectionBackground"));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(0, 204, 204));
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(0, 204, 204));

        mainTabPane.setBackground(new java.awt.Color(0, 204, 204));

        enterTweetLabel.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        enterTweetLabel.setText("Enter your Tweet:");

        enterTweetTextArea.setColumns(20);
        enterTweetTextArea.setLineWrap(true);
        enterTweetTextArea.setRows(5);
        tweetTextArea.setViewportView(enterTweetTextArea);

        updateButton.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createTweetPanelLayout = new javax.swing.GroupLayout(createTweetPanel);
        createTweetPanel.setLayout(createTweetPanelLayout);
        createTweetPanelLayout.setHorizontalGroup(
            createTweetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createTweetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tweetTextArea)
                .addContainerGap())
            .addGroup(createTweetPanelLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createTweetPanelLayout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(enterTweetLabel)
                .addGap(96, 96, 96))
        );
        createTweetPanelLayout.setVerticalGroup(
            createTweetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createTweetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enterTweetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tweetTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        mainTabPane.addTab("Compose a Tweet", createTweetPanel);

        searchTopicLabel.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        searchTopicLabel.setText("Search for:");

        searchTopicTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTopicTextFieldActionPerformed(evt);
            }
        });

        searchTopicsButton.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        searchTopicsButton.setText("Search Topics");
        searchTopicsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTopicsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchTopicsPanelLayout = new javax.swing.GroupLayout(searchTopicsPanel);
        searchTopicsPanel.setLayout(searchTopicsPanelLayout);
        searchTopicsPanelLayout.setHorizontalGroup(
            searchTopicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchTopicsPanelLayout.createSequentialGroup()
                .addGroup(searchTopicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchTopicsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(searchTopicTextField))
                    .addGroup(searchTopicsPanelLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(searchTopicLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(searchTopicsPanelLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(searchTopicsButton)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        searchTopicsPanelLayout.setVerticalGroup(
            searchTopicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchTopicsPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(searchTopicLabel)
                .addGap(18, 18, 18)
                .addComponent(searchTopicTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchTopicsButton)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        mainTabPane.addTab("Search Topics", searchTopicsPanel);

        searchPeopleLabel.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        searchPeopleLabel.setText("Search for:");

        searchPeopleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPeopleTextFieldActionPerformed(evt);
            }
        });

        searchPeopleButton.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        searchPeopleButton.setText("Search People");
        searchPeopleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPeopleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPeoplePanelLayout = new javax.swing.GroupLayout(searchPeoplePanel);
        searchPeoplePanel.setLayout(searchPeoplePanelLayout);
        searchPeoplePanelLayout.setHorizontalGroup(
            searchPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPeoplePanelLayout.createSequentialGroup()
                .addGroup(searchPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPeoplePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(searchPeopleTextField))
                    .addGroup(searchPeoplePanelLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(searchPeopleLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(searchPeoplePanelLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(searchPeopleButton)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        searchPeoplePanelLayout.setVerticalGroup(
            searchPeoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPeoplePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(searchPeopleLabel)
                .addGap(18, 18, 18)
                .addComponent(searchPeopleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchPeopleButton)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        mainTabPane.addTab("Search People", searchPeoplePanel);

        profilePanel.setBackground(new java.awt.Color(0, 204, 204));

        profileLabel.setFont(new java.awt.Font("Aharoni", 3, 24)); // NOI18N
        profileLabel.setForeground(new java.awt.Color(255, 255, 255));
        profileLabel.setText("PROFILE:");

        nameLabel.setBackground(new java.awt.Color(255, 255, 255));
        nameLabel.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Name:");

        usernameLabel.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        usernameLabel.setText("Username:");

        followingLabel.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        followingLabel.setForeground(new java.awt.Color(255, 255, 255));
        followingLabel.setText("Following:");

        followersLabel.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        followersLabel.setForeground(new java.awt.Color(255, 255, 255));
        followersLabel.setText("Followers:");

        nameLabelContent.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        nameLabelContent.setForeground(new java.awt.Color(255, 255, 255));
        nameLabelContent.setText(engine.getUserInformation()[0]);

        displayNameLabelContent.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        displayNameLabelContent.setForeground(new java.awt.Color(255, 255, 255));
        displayNameLabelContent.setText(engine.getUserInformation()[1]);

        followingLabelContent.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        followingLabelContent.setForeground(new java.awt.Color(255, 255, 255));
        followingLabelContent.setText(engine.getUserInformation()[2]);

        followersLabelContent.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        followersLabelContent.setForeground(new java.awt.Color(255, 255, 255));
        followersLabelContent.setText(engine.getUserInformation()[3]);

        tweetLabel.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        tweetLabel.setForeground(new java.awt.Color(255, 255, 255));
        tweetLabel.setText("Tweets:");

        tweetContentLabel.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        tweetContentLabel.setForeground(new java.awt.Color(255, 255, 255));
        tweetContentLabel.setText(engine.getUserInformation()[4]);

        timelineButton.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        timelineButton.setText("View My Timeline");
        timelineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timelineButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameLabelContent))
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addComponent(usernameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayNameLabelContent))
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addComponent(followingLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(followingLabelContent))
                    .addComponent(profileLabel)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addComponent(followersLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(followersLabelContent))
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addComponent(tweetLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tweetContentLabel))
                    .addComponent(timelineButton))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addComponent(profileLabel)
                .addGap(1, 1, 1)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameLabelContent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(displayNameLabelContent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(followingLabel)
                    .addComponent(followingLabelContent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(followersLabel)
                    .addComponent(followersLabelContent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tweetLabel)
                    .addComponent(tweetContentLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(timelineButton))
        );

        twitterPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/twitterimage.jpg"))); // NOI18N

        switchAccountButton.setFont(new java.awt.Font("Aharoni", 0, 12)); // NOI18N
        switchAccountButton.setText("Switch Account");
        switchAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchAccountButtonActionPerformed(evt);
            }
        });

        tweetTable.setModel(engine.getTable());
        tweetTable.getTableHeader().setReorderingAllowed(false);
        tweetTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tweetTableMouseClicked(evt);
            }
        });
        tweetTableScrollPane.setViewportView(tweetTable);

        displayTweetText.setColumns(20);
        displayTweetText.setLineWrap(true);
        displayTweetText.setRows(5);

        followButton.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        followButton.setText("Follow");
        followButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                followButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        retweetButton.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        retweetButton.setText("Retweet");
        retweetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retweetButtonActionPerformed(evt);
            }
        });

        trendsFollowersPanel.setBackground(new java.awt.Color(255, 255, 255));
        trendsFollowersPanel.setOpaque(false);

        trendLabel.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        trendLabel.setForeground(new java.awt.Color(255, 255, 255));
        trendLabel.setText("TOP TRENDS");

        followerLabel.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        followerLabel.setForeground(new java.awt.Color(255, 255, 255));
        followerLabel.setText("WHO TO FOLLOW");

        trendsList.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        trendsList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        trendsListScrollPane.setViewportView(trendsList);

        followersList.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        followersList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        followersListScrollPane.setViewportView(followersList);

        javax.swing.GroupLayout trendsFollowersPanelLayout = new javax.swing.GroupLayout(trendsFollowersPanel);
        trendsFollowersPanel.setLayout(trendsFollowersPanelLayout);
        trendsFollowersPanelLayout.setHorizontalGroup(
            trendsFollowersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(trendsListScrollPane)
            .addComponent(followersListScrollPane)
            .addGroup(trendsFollowersPanelLayout.createSequentialGroup()
                .addGroup(trendsFollowersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trendLabel)
                    .addComponent(followerLabel))
                .addGap(0, 85, Short.MAX_VALUE))
        );
        trendsFollowersPanelLayout.setVerticalGroup(
            trendsFollowersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trendsFollowersPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(trendLabel)
                .addGap(1, 1, 1)
                .addComponent(trendsListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(followerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(followersListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tweetTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mainTabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addComponent(displayTweetText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(retweetButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                    .addComponent(deleteButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(followButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(twitterPic)
                            .addComponent(profilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trendsFollowersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(switchAccountButton)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(mainTabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(retweetButton))
                                    .addComponent(followButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteButton))
                            .addComponent(displayTweetText, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tweetTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(switchAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trendsFollowersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(twitterPic, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(profilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(228, 228, 228)))
                .addGap(761, 761, 761))
        );

        fileMenu.setText("File");

        refreshMenuItem.setText("Refresh");
        fileMenu.add(refreshMenuItem);

        quitMenuItem.setText("Quit");
        quitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(quitMenuItem);

        menubar.add(fileMenu);

        helpMenuBar.setText("Help");

        getHelpMenuItem.setText("Get Help");
        helpMenuBar.add(getHelpMenuItem);

        menubar.add(helpMenuBar);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private static final Logger LOG = Logger.getLogger(Twitter4JGUI.class.getName());

    private void quitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitMenuItemActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try {
            int index = tweetTable.getSelectedRow();
            if (index != -1){
                long sid = engine.getTable().get(index).getId();
                engine.deleteTweet(sid);
            }
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Delete failed.");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void retweetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retweetButtonActionPerformed
        try {
            int index = tweetTable.getSelectedRow();
            if (index != -1){
                long sid = engine.getTable().get(index).getId();
                engine.retweet(sid);
            }
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Retweet failed.");
        }
    }//GEN-LAST:event_retweetButtonActionPerformed

    private void followButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_followButtonActionPerformed
        try{
            int index = tweetTable.getSelectedRow();
            if (index != -1){
                long id = engine.getTable().get(index).getId();
                engine.followUser(id);
            }
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Follow failed.");
        }
    }//GEN-LAST:event_followButtonActionPerformed

    private void tweetTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tweetTableMouseClicked
        int index = tweetTable.getSelectedRow();
        if (index != -1) {
            Tweet t = engine.getTable().get(index);
            displayTweetText.setText(t.getText());
        }
    }//GEN-LAST:event_tweetTableMouseClicked

    private void switchAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchAccountButtonActionPerformed
        switchAccountDialog.setVisible(true);
    }//GEN-LAST:event_switchAccountButtonActionPerformed

    private void searchTopicsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTopicsButtonActionPerformed
        try {
            engine.searchTweets(searchTopicTextField.getText());
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Search topics failed.");
        }
    }//GEN-LAST:event_searchTopicsButtonActionPerformed

    private void searchTopicTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTopicTextFieldActionPerformed
        try{
            engine.searchTweets(searchTopicTextField.getText());
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Search topics failed.");
        }
    }//GEN-LAST:event_searchTopicTextFieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        try {
            engine.updateStatus(enterTweetTextArea.getText());
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Update status failed.");
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void searchPeopleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPeopleTextFieldActionPerformed
        try{
            engine.searchPeople(searchPeopleTextField.getText());
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Search people failed.");
        }
    }//GEN-LAST:event_searchPeopleTextFieldActionPerformed

    private void searchPeopleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPeopleButtonActionPerformed
        try{
            engine.searchPeople(searchPeopleTextField.getText());
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Search people failed.");
        }
    }//GEN-LAST:event_searchPeopleButtonActionPerformed

    private void timelineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timelineButtonActionPerformed
        try{
            engine.showTimeLine();
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Updating timeline failed.");
        }
    }//GEN-LAST:event_timelineButtonActionPerformed

    private void consumerKeyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consumerKeyTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consumerKeyTextFieldActionPerformed

    private void accessTokenTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accessTokenTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accessTokenTextFieldActionPerformed

    private void switchAccountDialogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchAccountDialogButtonActionPerformed
        try{
            String consumerKey = consumerKeyTextField.getText();
            String consumerSecret = consumerSecretTextField.getText();
            String accessToken = accessTokenTextField.getText();
            String accessTokenSecret = accessTokenSecretTextField.getText();
            engine.switchAccount(consumerKey, consumerSecret, accessToken, accessTokenSecret);
            updateUserInformation();
            switchAccountDialog.setVisible(false);
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Switch account failed.");
        }
    }//GEN-LAST:event_switchAccountDialogButtonActionPerformed
    
    private void updateUserInformation(){
        nameLabelContent.setText(engine.getUserInformation()[0]);
        displayNameLabelContent.setText(engine.getUserInformation()[1]);
        followingLabelContent.setText(engine.getUserInformation()[2]);
        followersLabelContent.setText(engine.getUserInformation()[3]);
        tweetContentLabel.setText(engine.getUserInformation()[4]);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Twitter4JGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Twitter4JGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Twitter4JGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Twitter4JGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Twitter4JGUI().setVisible(true);
                } catch (Exception e){
                    JOptionPane.showMessageDialog(null, "An error has occurred.");
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accessTokenLabel;
    private javax.swing.JLabel accessTokenSecretLabel;
    private javax.swing.JTextField accessTokenSecretTextField;
    private javax.swing.JTextField accessTokenTextField;
    private javax.swing.JLabel consumerKeyLabel;
    private javax.swing.JTextField consumerKeyTextField;
    private javax.swing.JLabel consumerSecretLabel;
    private javax.swing.JTextField consumerSecretTextField;
    private javax.swing.JPanel createTweetPanel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel displayNameLabelContent;
    private javax.swing.JTextArea displayTweetText;
    private javax.swing.JLabel enterTweetLabel;
    private javax.swing.JTextArea enterTweetTextArea;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton followButton;
    private javax.swing.JLabel followerLabel;
    private javax.swing.JLabel followersLabel;
    private javax.swing.JLabel followersLabelContent;
    private javax.swing.JList followersList;
    private javax.swing.JScrollPane followersListScrollPane;
    private javax.swing.JLabel followingLabel;
    private javax.swing.JLabel followingLabelContent;
    private javax.swing.JMenuItem getHelpMenuItem;
    private javax.swing.JMenu helpMenuBar;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTabbedPane mainTabPane;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabelContent;
    private javax.swing.JLabel profileLabel;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JMenuItem quitMenuItem;
    private javax.swing.JMenuItem refreshMenuItem;
    private javax.swing.JButton retweetButton;
    private javax.swing.JButton searchPeopleButton;
    private javax.swing.JLabel searchPeopleLabel;
    private javax.swing.JPanel searchPeoplePanel;
    private javax.swing.JTextField searchPeopleTextField;
    private javax.swing.JLabel searchTopicLabel;
    private javax.swing.JTextField searchTopicTextField;
    private javax.swing.JButton searchTopicsButton;
    private javax.swing.JPanel searchTopicsPanel;
    private javax.swing.JButton switchAccountButton;
    private javax.swing.JDialog switchAccountDialog;
    private javax.swing.JButton switchAccountDialogButton;
    private javax.swing.JPanel switchAccountPanel;
    private javax.swing.JLabel switchAccountPromptLabel;
    private javax.swing.JButton timelineButton;
    private javax.swing.JLabel trendLabel;
    private javax.swing.JPanel trendsFollowersPanel;
    private javax.swing.JList trendsList;
    private javax.swing.JScrollPane trendsListScrollPane;
    private javax.swing.JLabel tweetContentLabel;
    private javax.swing.JLabel tweetLabel;
    private javax.swing.JTable tweetTable;
    private javax.swing.JScrollPane tweetTableScrollPane;
    private javax.swing.JScrollPane tweetTextArea;
    private javax.swing.JLabel twitterPic;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
    private TwitterEngine engine;
}
